import pandas as pd
sheets1 = pd.read_excel('demodata.xlsx','Sheet1')
a=sheets1.to_csv('sheet1.csv')
sheets2 = pd.read_excel('demodata.xlsx','Sheet2')
b=sheets2.to_csv('sheet2.csv')
sheets3 = pd.read_excel('demodata.xlsx','Sheet3')
c=sheets3.to_csv('sheet3.csv')
sheets4 = pd.read_excel('demodata.xlsx','Sheet4')
d=sheets4.to_csv('sheet4.csv')
sheets5 = pd.read_excel('demodata.xlsx','Sheet5')
e=sheets5.to_csv('sheet5.csv')
sheets6= pd.read_excel('demodata.xlsx','Sheet6')
f=sheets6.to_csv('sheet6.csv')
sheets6= pd.read_excel('demodata.xlsx','Sheet7')
g=sheets6.to_csv('sheet7.csv')
sheets4 = pd.read_excel('demodata.xlsx','Sheet8')
h=sheets4.to_csv('sheet8.csv')
sheets5 = pd.read_excel('demodata.xlsx','Sheet9')
i=sheets5.to_csv('sheet9.csv')
sheets10= pd.read_excel('demodata.xlsx','Sheet10')
j=sheets10.to_csv('sheet10.csv')
print("done")